server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  type-aliases-package: com.zc.security.mapper
  mapper-locations: classpath:mapper/*.xml